### ISSUE TITLE
Items for Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#110]
For #1 

- [x] Singularity when an object is placed exactly at the focal point that results in an infinitely large image - #103 
- [x] Guides correspond to marginal rays when the object distance = 2f. 
- [x] Ray path through diverging lens - https://github.com/phetsims/geometric-optics/issues/124
- [x] Perspective of the picture frames implies that the observer is looking from the side. Technically you would only see an image from this vantage point if there was a screen at the image location. Then, light would reflect from the screen and get focused onto your retina.
- [x] Public query parameters in https://github.com/phetsims/geometric-optics/blob/master/js/common/GOQueryParameters.ts
- [x] Purpose of show/hide button - #188 
- [x] Principal Ray representation - #140 
- [x] #288 
- [x] We do not model the physics of reflected rays and they may pass over the object.  https://github.com/phetsims/geometric-optics/issues/125
- [x] For consistency, labels appear below the item. For objects, this means that the "object" label may not be immediately next to the origin of the point source. #308 
- [x] Focal length and radius of curvature titles indicate the sign of the value.
- [x] ROC & FL controls disappear when mirror is flat - values are infinite.
- [x] Flat mirror is intended for comparison purposes, but learning goals centered around flat mirrors are better served by Geometric Optics: Basics (centered mirror, free-moving objects).
- [x] Intensity algorithms - #335 #350 
- [x] Many rays consists of a 120-degree fan of rays. The number of rays increases with the distance of the object from the optic, so that at least 2 rays will pass through the optic. #289 #405
- [x] The minimum object distance is 40 cm, so placing the object at the focal point may not always be possible.

**Comment by pixelzoom** [comment]
- [ ] Information about the "Guides" feature. From comments in the code, my understanding is that this is a representation invented by PhET.  And I'm still trying to figure it out myself :)

**Comment by pixelzoom** [comment]
Per https://github.com/phetsims/geometric-optics/issues/417...  In the Light scene, rays that do not interact with the lens will not cast any light on the projection screen, because we are not modeling ambient light.  For example, in the case below, some of the "Many" rays hit the screen, but they do not interact with the optic.

<img width="1104" alt="screenshot_1640" src="https://user-images.githubusercontent.com/3046552/161578108-519fc6df-a013-4c7e-a0a0-d58be53c6bc7.png">

**Comment by arouinfar** [comment]
Tips have been uploaded to the site, closing.
