### ISSUE TITLE
Publish Dev version 1.0

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#77]
The goal is to publish a first dev version on 7/8/2021.  We will ask @chrisklus for help to deploy it to Bayes.

**Comment by sarchang** [comment]
Remaining tasks in order of priority:

- [ ] Change default sim setup (#75)
- [ ] Rays should come from light bulb, not middle of lamp (#79)
- [ ] Rays should stop at the screen (#13)
- [ ] Add other images of the tree in different orientations (#78)
- [ ] Add other images of the rocket in different orientations (#78)
- [ ] Tree: Manually adjust where the rays intersect the object and the image such that it is consistent with artwork
- [ ] Rocket: Manually adjust where the rays intersect the object and the image such that it is consistent with artwork
- [ ] Add dotted line in the middle of optic for principal rays (#76)
- [ ] Add cueing arrows on Second Source red dot (#81)
- [ ] Spotlight on the screen should be drawn when rays reach the screen, not when the rays converge (#69)
- [ ] Drag bounds: optic (#57), second source of light (#58)
- [ ] Labels: adjust positioning, increase text size (#24)

**Comment by sarchang** [comment]
Link to dev version: https://phet-dev.colorado.edu/html/geometric-optics/1.0.0-dev.1/phet/geometric-optics_en_phet.html

**Comment by veillette** [comment]
The dev version was published. 
Some of these issues have not ben tackled but we are now tracking relevant issues on a project Board. Closing
